rs, sys: bump capstone to 6.0.0-Alpha8

diff --git a/capstone-sys/capstone/.github/workflows/CITest.yml b/capstone-sys/capstone/.github/workflows/CITest.yml
--- a/capstone-sys/capstone/.github/workflows/CITest.yml
+++ b/capstone-sys/capstone/.github/workflows/CITest.yml
@@ -193,13 +193,13 @@ jobs:
         valgrind --leak-check=full cstest tests/MC
 
     - name: Compatibility header generation
-      # clang-format-17 is only available in Ubuntu 24.04
+      # clang-format-20 is only available in Ubuntu 24.04
       # Hence the check only happens for it.
       if: startsWith(matrix.config.build-system, 'cmake') && startsWith(matrix.config.os, 'ubuntu-24.04')
       run: |
         sudo apt-get -y update
-        sudo apt-get -y install clang-format-17
-        clang-format-17 --version
+        sudo apt-get -y install clang-format-20
+        clang-format-20 --version
         cp ./include/capstone/arm64.h arm64_compat_current.h
         cp ./include/capstone/systemz_compatibility.h systemz_compat_current.h
         ./suite/auto-sync/src/autosync/HeaderPatcher.py -C ./.clang-format -c --v6 ./include/capstone/aarch64.h --v5 ./include/capstone/arm64.h
@@ -232,8 +232,23 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
-    - uses: lukka/get-cmake@latest
-      name: Get CMake
+    - name: 'Install cmake'
+      if: contains(matrix.config.name, 'MSVC 64')
+      env:
+        CMAKE_VER: '4.3.2'
+        CMAKE_MSI_SHA256: '6915813bedf3a8a698b72fc858e0c2a99761be981745c3c3c99bd30e1477e142'
+      shell: powershell
+      run: |
+        $cmake_msi_url = "https://github.com/Kitware/CMake/releases/download/v$env:CMAKE_VER/cmake-$env:CMAKE_VER-windows-x86_64.msi"
+        Invoke-WebRequest -Uri $cmake_msi_url -OutFile "cmake.msi"
+        $computedHash = Get-FileHash -Path "cmake.msi" -Algorithm SHA256
+        if ($computedHash.Hash -ne $env:CMAKE_MSI_SHA256) {
+          Write-Error "Hash verification failed! File may be corrupted."
+          exit 1
+        } else {
+          Write-Host "Hash verification successful!"
+        }
+        Start-Process msiexec.exe -ArgumentList "/qn /i cmake.msi" -Wait
 
     - name: '🛠️ Win MSVC 64 setup'
       if: contains(matrix.config.name, 'MSVC 64')
